name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -f backend/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/needle:${{ github.sha }} \
            ./backend

      - name: Tag Image with Short Commit SHA
        run: |
          SHORT_SHA="${{ github.sha }}"
          SHORT_SHA="${SHORT_SHA:0:7}"
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/needle:${{ github.sha }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/needle:${SHORT_SHA}

      - name: Tag Image as Latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/needle:${{ github.sha }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/needle:latest

      - name: Push All Tags
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/needle:${{ github.sha }}
          SHORT_SHA="${{ github.sha }}"
          SHORT_SHA="${SHORT_SHA:0:7}"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/needle:${SHORT_SHA}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/needle:latest
