name: Build and Release needlectl

on:
  push:
    branches:
      - main
    paths:
      - needlectl/**

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Get the commit hash
      - name: Get commit hash
        id: get_commit_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies and build needlectl
      - name: Build needlectl
        run: |
          cd needlectl
          chmod +x build.sh
          ./build.sh

      # Archive the binary
      - name: Archive the binary
        run: |
          mkdir -p release
          mv needlectl/dist/needlectl release/

      # Create the release with commit hash as the tag
      - name: Create Release with Commit Hash
        id: create_release_commit_hash
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.hash }}
          name: "needlectl (${env.hash})"
          artifacts: release/needlectl
          replacesArtifacts: 'true'

      # Add the "latest" tag to the same release
      - name: Create or Update "latest" Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f latest
          git push origin --tags --force

      # Add an optional step to clean up
      - name: Clean up
        run: |
          rm -rf needlectl/dist needlectl/build needlectl/build_env release
